# Generated by Django 5.1.7 on 2025-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='tree.person')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
